#!/usr/bin/env bash
# Check if correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="ubuntu"
ssh_key="~/.ssh/id_rsa"

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/
