#!/usr/bin/env bash
# Update package list and install Nginx
apt-get -y update
apt-get -y install nginx

# Create a custom index.html file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx to apply changes
service nginx restart

# End of script
