#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}

# Check if no arguments are provided
if [ $# -eq 0 ]
then
echo "Usage: $0 {IP_ADDRESS}"
else
# Use ping to send 5 ICMP echo requests to the specified IP address
ping -c 5 "$1"
fi
