#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

# Check if an IP address argument is provided
if [ $# -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	# Use ping to send 5 ICMP echo requests to the provided IP address
	ping -c 5 "$1"
fi
