#!/usr/bin/env bash
# Manages the script manage_my_process.

if [ $# -ne 1 ]; then
	echo "Usage: $0 {start|stop|restart}"
	exit 1
fi

if [ "$1" == "start" ]; then
	if [ -f /var/run/my_process.pid ]; then
		echo "manage_my_process is already running."
		exit 1
	fi

	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
	if [ -f /var/run/my_process.pid ]; then
		echo "manage_my_process stopped"
		kill "$(cat /var/run/my_process.pid)"
		rm /var/run/my_process.pid
	else
		echo "manage_my_process is not running."
		exit 1
	fi
elif [ "$1" == "restart" ]; then
	if [ -f /var/run/my_process.pid ]; then
		echo "manage_my_process restarted"
		kill "$(cat /var/run/my_process.pid)"
		rm /var/run/my_process.pid
	fi

	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
else
	echo "Usage: $0 {start|stop|restart}"
	exit 1
fi
