#!/usr/bin/env bash

# Function to start the process and create PID file
start_process() {
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}

# Function to stop the process and delete PID file
stop_process() {
	if [ -f /var/run/my_process.pid ]; then
		echo "manage_my_process stopped"
		kill "$(cat /var/run/my_process.pid)"
		rm /var/run/my_process.pid
	else
		echo "manage_my_process is not running"
	fi
}

# Function to restart the process
restart_process() {
	stop_process
	start_process
	echo "manage_my_process restarted"
}

# Check for command-line arguments
if [ $# -eq 1 ]; then
	case $1 in
		"start")
			start_process
			;;
		"stop")
			stop_process
			;;
		"restart")
			restart_process
			;;
		*)
			echo "Usage: manage_my_process {start|stop|restart}"
			;;
	esac
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
