#!/usr/bin/env bash
# This script displays user information from /etc/passwd using the while loop + IFS.

while IFS=: read -r username _ uid gid _ home shell; do
read -r _ password_info _ <<< "$(grep -E "^$username:" /etc/shadow)"
echo "The user $username is part of the group $gid gang,"
echo "lives in $home and rides $shell."
echo "User ID's place is protected by the passcode $password_info,"
echo "more info about the user here: USER ID INFO"
echo "-----------------------------------"
done < /etc/passwd
