#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop.

count=0  # Initialize a counter

until [ "$count" -ge 10 ]; do
echo "Best School"
count=$((count + 1))  # Increment the counter
done
