#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with custom messages.

count=1  # Initialize the loop counter

while [ "$count" -le 20 ]; do
case "$count" in
4)
echo "$count and then bad luck from China"
;;
9)
echo "$count and then bad luck from Japan"
;;
17)
echo "$count and then bad luck from Italy"
;;
*)
echo "$count"  # Display the number for other iterations
;;
esac

count=$((count + 1))  # Increment the loop counter
done
